# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-18 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(blank=True, max_length=10, verbose_name='Salt'),
        ),
    ]
