# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-12 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20180612_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.NullBooleanField(verbose_name='Gender'),
        ),
    ]
