# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-12 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20180612_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
