# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-12 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20180612_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=0, max_length=18, unique=True, verbose_name='Phone'),
        ),
    ]
