# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-12 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_auto_20180612_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default=0, max_length=18, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
