# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-20 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_auto_20180619_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
