# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-06 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_auto_20180629_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='start_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
