# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-14 05:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=30)),
                ('start_date', models.DateField(default=datetime.datetime(2018, 6, 14, 5, 58, 24, 293858, tzinfo=utc))),
                ('age_level', models.CharField(choices=[('Kidergarten', 'Kindergarten'), ('Elementary', 'Elementary'), ('Middle', 'Middle')], default='A', max_length=15)),
                ('location', models.CharField(max_length=20)),
                ('contract_period', models.CharField(max_length=20)),
                ('day_hour', models.CharField(max_length=50)),
                ('min_salary', models.FloatField()),
                ('max_salary', models.FloatField()),
                ('flight_support', models.CharField(choices=[('none', 'none'), ('one-way', 'one-way'), ('round-trip', 'round-trip')], default='A', max_length=15)),
                ('house', models.BooleanField()),
                ('house_pic', models.FileField(upload_to='')),
                ('severance_payment', models.BooleanField()),
                ('health_insurance', models.BooleanField()),
                ('national_pension', models.BooleanField()),
            ],
        ),
    ]
