# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-14 06:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_job_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_info',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job_info',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 14, 6, 39, 16, 360108, tzinfo=utc)),
        ),
    ]
