# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-17 09:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0004_auto_20180615_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_apply',
            old_name='address',
            new_name='cur_residence',
        ),
        migrations.RenameField(
            model_name='job_apply',
            old_name='certification_text',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='job_apply',
            old_name='qual_time',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='criminal',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='criminal_text',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='education',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='family',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='freind',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='freind_name',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='good_time',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='housing',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='influx',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='korean_level',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='medical',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='office',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='prefer_location',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='second_location',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='visa',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='wanted_salary',
        ),
        migrations.AddField(
            model_name='job_apply',
            name='skyid',
            field=models.CharField(default='a', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_apply',
            name='country',
            field=models.CharField(choices=[('USA', 'USA'), ('Canada', 'Canada'), ('UK', 'UK'), ('Ireland', 'Ireland'), ('South Africa', 'South Africa'), ('New Zealand', 'New Zealand'), ('Australia', 'Australia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job_apply',
            name='degree',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='job_apply',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='job_apply',
            name='prefer_class',
            field=models.CharField(choices=[('Kindergarten', 'Kindergarten'), ('Elementary', 'Elementary'), ('Middle', 'Middle')], default='A', max_length=15),
        ),
        migrations.AlterField(
            model_name='job_info',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 17, 9, 12, 14, 674845, tzinfo=utc)),
        ),
    ]
