# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-18 15:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0005_auto_20180617_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_info',
            old_name='house_pic',
            new_name='house_pic1',
        ),
        migrations.AddField(
            model_name='job_info',
            name='house_pic2',
            field=models.FileField(default='a', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_info',
            name='house_pic3',
            field=models.FileField(default='a', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_info',
            name='house_pic4',
            field=models.FileField(default='a', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_info',
            name='house_pic5',
            field=models.FileField(default='a', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_info',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 18, 14, 59, 39, 457601, tzinfo=utc)),
        ),
    ]
