# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 01:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0006_auto_20180619_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_apply',
            name='profile_image1',
            field=models.ImageField(default='a', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_apply',
            name='profile_image2',
            field=models.ImageField(default='a', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_info',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 19, 1, 26, 0, 235443, tzinfo=utc)),
        ),
    ]
