# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 03:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0007_auto_20180619_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_apply',
            name='gender',
            field=models.CharField(choices=[('MAN', 'MAN'), ('WOMAN', 'WOMAN')], max_length=10),
        ),
        migrations.AlterField(
            model_name='job_info',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 19, 3, 43, 22, 451870, tzinfo=utc)),
        ),
    ]
