# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 11:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0008_auto_20180619_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_apply',
            name='introduction',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_apply',
            name='letter',
            field=models.FileField(default='a', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_info',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 19, 11, 43, 30, 744424, tzinfo=utc)),
        ),
    ]
