# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-20 04:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0012_auto_20180620_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_info',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 20, 4, 59, 43, 342573, tzinfo=utc)),
        ),
    ]
