# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-20 06:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0013_auto_20180620_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_info',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job_info',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 20, 6, 27, 13, 47808, tzinfo=utc)),
        ),
    ]
